"""Frozen public enumerations for the Problem Locator V1 contract."""

from __future__ import annotations

from enum import StrEnum


class CaseStatus(StrEnum):
    NEW = "NEW"
    RUNNING = "RUNNING"
    WAITING_INPUT = "WAITING_INPUT"
    WAITING_ATTACHMENT = "WAITING_ATTACHMENT"
    REVIEWING = "REVIEWING"
    RESOLVED = "RESOLVED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    INTERRUPTED = "INTERRUPTED"


class JobStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    INTERRUPTED = "INTERRUPTED"


class JobType(StrEnum):
    ROUTE = "ROUTE"
    DIAGNOSE = "DIAGNOSE"
    REVIEW = "REVIEW"


class OutcomeDisposition(StrEnum):
    APPLIED = "APPLIED"
    DUPLICATE = "DUPLICATE"
    STALE = "STALE"
    REJECTED = "REJECTED"


class FailureReportDisposition(StrEnum):
    APPLIED = "APPLIED"
    DUPLICATE = "DUPLICATE"
    STALE = "STALE"


class OutcomeResultType(StrEnum):
    COMPLETED = "COMPLETED"
    NEED_INPUT = "NEED_INPUT"
    NEED_ATTACHMENT = "NEED_ATTACHMENT"
    REROUTE = "REROUTE"
    NO_CAPABILITY = "NO_CAPABILITY"
    FAILED = "FAILED"


class AttachmentStatus(StrEnum):
    UPLOADING = "UPLOADING"
    READY = "READY"
    FAILED = "FAILED"


class CandidateStatus(StrEnum):
    PROPOSED = "PROPOSED"
    REVIEWING = "REVIEWING"
    REJECTED = "REJECTED"
    ACCEPTED = "ACCEPTED"


class ReviewVerdict(StrEnum):
    PASS = "PASS"
    NEED_MORE_EVIDENCE = "NEED_MORE_EVIDENCE"
    REJECT = "REJECT"


class RouteKind(StrEnum):
    MATCHED = "MATCHED"
    NO_CAPABILITY = "NO_CAPABILITY"


class RequirementKind(StrEnum):
    INPUT = "INPUT"
    ATTACHMENT = "ATTACHMENT"


class RequirementStatus(StrEnum):
    OPEN = "OPEN"
    FULFILLED = "FULFILLED"


class ArtifactKind(StrEnum):
    USER_RESULT = "USER_RESULT"
    DIAGNOSTIC_EXPORT = "DIAGNOSTIC_EXPORT"
    LOGPARSE_RUN = "LOGPARSE_RUN"


class ResourceKind(StrEnum):
    FILE = "FILE"
    DIRECTORY = "DIRECTORY"


class CancellationReason(StrEnum):
    USER_CANCEL = "USER_CANCEL"
    SERVICE_SHUTDOWN = "SERVICE_SHUTDOWN"


class DiagnosisItemStatus(StrEnum):
    ACTIVE = "ACTIVE"
    RESOLVED = "RESOLVED"
    REJECTED = "REJECTED"
    SUPERSEDED = "SUPERSEDED"


class DiagnosisProvenanceType(StrEnum):
    USER_INPUT = "USER_INPUT"
    AGENT_OUTCOME = "AGENT_OUTCOME"


class FieldUpdateAction(StrEnum):
    SET = "SET"
    CLEAR = "CLEAR"


class CandidateMutationAction(StrEnum):
    INSTALL = "INSTALL"
    SET_STATUS = "SET_STATUS"


class EvidenceSourceType(StrEnum):
    USER_FACT = "USER_FACT"
    ATTACHMENT = "ATTACHMENT"
    LOGPARSE = "LOGPARSE"
    TOOL_OUTPUT = "TOOL_OUTPUT"
    PREVIOUS_OUTCOME = "PREVIOUS_OUTCOME"


class AssetKind(StrEnum):
    AGENT_PROFILE = "AGENT_PROFILE"
    DIAGNOSIS_SKILL = "DIAGNOSIS_SKILL"
    TOOL_BUNDLE = "TOOL_BUNDLE"
    CONTEXT_POLICY = "CONTEXT_POLICY"
    OUTPUT_CONTRACT = "OUTPUT_CONTRACT"
    LOGPARSE_TOOL = "LOGPARSE_TOOL"


class ExecutionStage(StrEnum):
    ASSET_RESOLUTION = "ASSET_RESOLUTION"
    CONTEXT_BUILD = "CONTEXT_BUILD"
    WORKSPACE_PREPARE = "WORKSPACE_PREPARE"
    BACKEND_START = "BACKEND_START"
    BACKEND_EXECUTE = "BACKEND_EXECUTE"
    TOOL_EXECUTE = "TOOL_EXECUTE"
    OUTCOME_VALIDATE = "OUTCOME_VALIDATE"
    RESOURCE_STAGE = "RESOURCE_STAGE"
    EXECUTION_RECORD = "EXECUTION_RECORD"


class ContextSectionKind(StrEnum):
    PROFILE = "PROFILE"
    SKILL = "SKILL"
    SKILL_INDEX = "SKILL_INDEX"
    TOOL_BUNDLE = "TOOL_BUNDLE"
    JOB_INSTRUCTION = "JOB_INSTRUCTION"
    CONTEXT_SNAPSHOT = "CONTEXT_SNAPSHOT"
    OPEN_REQUIREMENTS = "OPEN_REQUIREMENTS"
    REVIEW_TARGET = "REVIEW_TARGET"
    OUTPUT_CONTRACT = "OUTPUT_CONTRACT"
    PREVIOUS_OUTCOME = "PREVIOUS_OUTCOME"
    EVIDENCE = "EVIDENCE"
    RESOURCE_MANIFEST = "RESOURCE_MANIFEST"


class WorkspaceInputKind(StrEnum):
    ATTACHMENT = "ATTACHMENT"
    EVIDENCE = "EVIDENCE"
    ARTIFACT = "ARTIFACT"
    PREVIOUS_OUTCOME = "PREVIOUS_OUTCOME"


class TriggerType(StrEnum):
    CREATE_CASE = "CREATE_CASE"
    ROUTE_OUTCOME = "ROUTE_OUTCOME"
    DIAGNOSIS_OUTCOME = "DIAGNOSIS_OUTCOME"
    REVIEW_OUTCOME = "REVIEW_OUTCOME"
    SUBMIT_SUPPLEMENT = "SUBMIT_SUPPLEMENT"
    CANCEL_CASE = "CANCEL_CASE"
    RESUME_INTERRUPTED = "RESUME_INTERRUPTED"
    EXECUTION_FAILED = "EXECUTION_FAILED"
    ASSET_VERSION_UNAVAILABLE = "ASSET_VERSION_UNAVAILABLE"
    MARK_OLD_EPOCH_INTERRUPTED = "MARK_OLD_EPOCH_INTERRUPTED"
    STALE_ACTIVE_OUTCOME = "STALE_ACTIVE_OUTCOME"


class ErrorCode(StrEnum):
    VALIDATION_ERROR = "VALIDATION_ERROR"
    CASE_NOT_FOUND = "CASE_NOT_FOUND"
    JOB_NOT_FOUND = "JOB_NOT_FOUND"
    JOB_CASE_MISMATCH = "JOB_CASE_MISMATCH"
    ATTACHMENT_NOT_FOUND = "ATTACHMENT_NOT_FOUND"
    ARTIFACT_NOT_FOUND = "ARTIFACT_NOT_FOUND"
    RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND"
    INVALID_CASE_STATE = "INVALID_CASE_STATE"
    ACTIVE_JOB_EXISTS = "ACTIVE_JOB_EXISTS"
    NEW_CASE_REQUIRED = "NEW_CASE_REQUIRED"
    REVISION_CONFLICT = "REVISION_CONFLICT"
    IDEMPOTENCY_CONFLICT = "IDEMPOTENCY_CONFLICT"
    RESOURCE_CASE_MISMATCH = "RESOURCE_CASE_MISMATCH"
    ATTACHMENT_NOT_READY = "ATTACHMENT_NOT_READY"
    UPLOAD_INCOMPLETE = "UPLOAD_INCOMPLETE"
    RESOURCE_HASH_MISMATCH = "RESOURCE_HASH_MISMATCH"
    RESOURCE_SIZE_MISMATCH = "RESOURCE_SIZE_MISMATCH"
    RESOURCE_LIMIT_EXCEEDED = "RESOURCE_LIMIT_EXCEEDED"
    PATH_VIOLATION = "PATH_VIOLATION"
    CONTEXT_LIMIT = "CONTEXT_LIMIT"
    ASSET_VERSION_UNAVAILABLE = "ASSET_VERSION_UNAVAILABLE"
    OUTCOME_MISSING = "OUTCOME_MISSING"
    OUTCOME_INVALID = "OUTCOME_INVALID"
    BACKEND_START_FAILED = "BACKEND_START_FAILED"
    BACKEND_CANCELLED = "BACKEND_CANCELLED"
    BACKEND_TIMEOUT = "BACKEND_TIMEOUT"
    BACKEND_OUTPUT_LIMIT = "BACKEND_OUTPUT_LIMIT"
    BACKEND_EXIT_FAILED = "BACKEND_EXIT_FAILED"
    WORKSPACE_LIMIT = "WORKSPACE_LIMIT"
    WORKSPACE_PREPARE_FAILED = "WORKSPACE_PREPARE_FAILED"
    RESOURCE_STAGE_FAILED = "RESOURCE_STAGE_FAILED"
    EXECUTION_RECORD_FAILED = "EXECUTION_RECORD_FAILED"
    LOGPARSE_FAILED = "LOGPARSE_FAILED"
    LOGPARSE_OUTPUT_INVALID = "LOGPARSE_OUTPUT_INVALID"
    DISPATCH_REJECTED = "DISPATCH_REJECTED"
    CLAIM_REJECTED = "CLAIM_REJECTED"
    INSTANCE_LOCKED = "INSTANCE_LOCKED"
    STATE_CORRUPT = "STATE_CORRUPT"
    STATE_SCHEMA_UNSUPPORTED = "STATE_SCHEMA_UNSUPPORTED"
    STATE_WRITE_FAILED = "STATE_WRITE_FAILED"
    RESOURCE_PUBLISH_FAILED = "RESOURCE_PUBLISH_FAILED"
    CONFIG_INVALID = "CONFIG_INVALID"
    NO_CAPABILITY = "NO_CAPABILITY"


__all__ = [
    name
    for name, value in globals().items()
    if name != "StrEnum" and isinstance(value, type) and issubclass(value, StrEnum)
]
